// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	OLTPTPCCRequest
	OLTPTPCCResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OLTPTPCCRequest struct {
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *OLTPTPCCRequest) Reset()                    { *m = OLTPTPCCRequest{} }
func (m *OLTPTPCCRequest) String() string            { return proto.CompactTextString(m) }
func (*OLTPTPCCRequest) ProtoMessage()               {}
func (*OLTPTPCCRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OLTPTPCCRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type OLTPTPCCResponse struct {
	Error      string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Results    []byte `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"`
	OLTPOutput []byte `protobuf:"bytes,3,opt,name=OLTPOutput,proto3" json:"OLTPOutput,omitempty"`
}

func (m *OLTPTPCCResponse) Reset()                    { *m = OLTPTPCCResponse{} }
func (m *OLTPTPCCResponse) String() string            { return proto.CompactTextString(m) }
func (*OLTPTPCCResponse) ProtoMessage()               {}
func (*OLTPTPCCResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OLTPTPCCResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *OLTPTPCCResponse) GetResults() []byte {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *OLTPTPCCResponse) GetOLTPOutput() []byte {
	if m != nil {
		return m.OLTPOutput
	}
	return nil
}

func init() {
	proto.RegisterType((*OLTPTPCCRequest)(nil), "rpc.OLTPTPCCRequest")
	proto.RegisterType((*OLTPTPCCResponse)(nil), "rpc.OLTPTPCCResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Worker service

type WorkerClient interface {
	OLTPTPCC(ctx context.Context, in *OLTPTPCCRequest, opts ...grpc.CallOption) (*OLTPTPCCResponse, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) OLTPTPCC(ctx context.Context, in *OLTPTPCCRequest, opts ...grpc.CallOption) (*OLTPTPCCResponse, error) {
	out := new(OLTPTPCCResponse)
	err := grpc.Invoke(ctx, "/rpc.Worker/OLTPTPCC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Worker service

type WorkerServer interface {
	OLTPTPCC(context.Context, *OLTPTPCCRequest) (*OLTPTPCCResponse, error)
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_OLTPTPCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OLTPTPCCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).OLTPTPCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Worker/OLTPTPCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).OLTPTPCC(ctx, req.(*OLTPTPCCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OLTPTPCC",
			Handler:    _Worker_OLTPTPCC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}

func init() { proto.RegisterFile("main.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0xcc, 0xcc,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0xd2, 0xe4, 0xe2, 0xf7,
	0xf7, 0x09, 0x09, 0x08, 0x09, 0x70, 0x76, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe3, 0x62, 0x4b, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x82,
	0xf2, 0x94, 0x92, 0xb8, 0x04, 0x10, 0x4a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x44, 0xb8,
	0x58, 0x53, 0x8b, 0x8a, 0xf2, 0x8b, 0xc0, 0x4a, 0x39, 0x83, 0x20, 0x1c, 0x21, 0x09, 0x2e, 0xf6,
	0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x92, 0x62, 0x09, 0x26, 0xb0, 0x11, 0x30, 0xae, 0x90, 0x1c, 0x17,
	0x17, 0xc8, 0x0c, 0xff, 0xd2, 0x92, 0x82, 0xd2, 0x12, 0x09, 0x66, 0xb0, 0x24, 0x92, 0x88, 0x91,
	0x23, 0x17, 0x5b, 0x78, 0x7e, 0x51, 0x76, 0x6a, 0x91, 0x90, 0x39, 0x17, 0x07, 0xcc, 0x36, 0x21,
	0x11, 0xbd, 0xa2, 0x82, 0x64, 0x3d, 0x34, 0x77, 0x4a, 0x89, 0xa2, 0x89, 0x42, 0x9c, 0x94, 0xc4,
	0x06, 0xf6, 0x9d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x84, 0xe4, 0xab, 0x53, 0xeb, 0x00, 0x00,
	0x00,
}
